"""
  Some random tests.
"""

import re
import os

from swebench.harness.swing_utils import load_swingbench_dataset_json, load_swingbench_dataset

ignored_instance_id = ['nvidia-holoscan__holohub-419',
'electron__electron-46279',
'electron__electron-45435',
'godotengine__godot-100319',
'microsoft__terminal-17725',
'godotengine__godot-101156',
'bitcoin__bitcoin-31451',
'bitcoin__bitcoin-30762',
'bitcoin__bitcoin-29899',
'microsoft__terminal-18481',
'microsoft__terminal-17386',
'microsoft__terminal-17162',
'microsoft__terminal-16615',
'firebase__firebase-ios-sdk-13034',
'godotengine__godot-104318',
'godotengine__godot-104296',
'godotengine__godot-100702',
'ouster-lidar__ouster-ros-357',
'godotengine__godot-100247',
'bitcoin__bitcoin-31556',
'microsoft__terminal-17953',
'microsoft__terminal-17794',
'microsoft__terminal-17361',
'microsoft__terminal-17173',
'microsoft__terminal-17066',
'microsoft__terminal-16598',
'redboltz__async_mqtt-222',
'kubernetes-sigs__kubebuilder-4415',
'gohugoio__hugo-13289',
'lightningnetwork__lnd-8665',
'runatlantis__atlantis-5233',
'runatlantis__atlantis-3905',
'junegunn__fzf-4004',
'traefik__traefik-11270',
'AlistGo__alist-8243',
'AlistGo__alist-7591',
'AlistGo__alist-6324',
'jesseduffield__lazygit-4324',
'jesseduffield__lazygit-3667',
'prometheus__prometheus-16196',
'prometheus__prometheus-14292',
'gohugoio__hugo-13552',
'gohugoio__hugo-13376',
'gohugoio__hugo-12796',
'gohugoio__hugo-12576',
'fatedier__frp-4323',
'fatedier__frp-4152',
'algorandfoundation__nodekit-105',
'kubernetes-sigs__kubebuilder-4599',
'maxence-charriere__go-app-1044',
'junegunn__fzf-3649',
'syncthing__syncthing-9912',
'minio__minio-20895',
'moby__moby-47748',
'ollama__ollama-10226',
'caddyserver__caddy-6806',
'AlistGo__alist-8154',
'AlistGo__alist-7678',
'AlistGo__alist-6339',
'jesseduffield__lazygit-3412',
'ethereum__go-ethereum-29919',
'gohugoio__hugo-13383',
'gohugoio__hugo-13281',
'gohugoio__hugo-13195',
'gohugoio__hugo-12799',
'gohugoio__hugo-12641',
'gohugoio__hugo-12287',
'fatedier__frp-4477',
'etcd-io__etcd-18829',
'pytorch__TensorRT-3209',
'regro__regolith-1133',
'Deltares__Wflow.jl-512',
'bacalhau-project__bacalhau-4522',
'sio2project__sinol-make-227',
'plugwise__python-plugwise-664',
'JohnSnowLabs__langtest-1097',
'peeringdb__peeringdb-py-96',
'cpp-linter__cpp-linter-hooks-50',
'fniessink__toisto-773',
'privacera__paig-37',
'aptos-labs__aptos-core-14893',
'aptos-labs__aptos-core-14368',
'aptos-labs__aptos-core-14174',
'doodspav__patomic-36',
'compilerla__conventional-pre-commit-117',
'LLNL__Caliper-593',
'bancaditalia__black-it-86',
'cloud-custodian__tfparse-195',
'dalibo__check_patroni-75',
'hhursev__recipe-scrapers-1411',
'hhursev__recipe-scrapers-1174',
'qBraid__qBraid-737',
'PolicyEngine__policyengine-us-5268',
'PolicyEngine__policyengine-us-5059',
'tree-sitter-grammars__tree-sitter-yaml-5',
'DiamondLightSource__httomo-380',
'j-andrews7__kenpompy-98',
'pandas-dev__pandas-stubs-995',
'tapdata__tapdata-2211',
'parflow__parflow-557',
'XiaoMi__MiNLP-238',
'deephaven__deephaven-plugins-448',
'alexklibisz__elastiknn-653',
'qutech__qupulse-829',
'griptape-ai__griptape-1055',
'skyflowapi__skyflow-python-123',
'WenjieDu__PyPOTS-512',
'PlasmaFAIR__fortitude-169',
'computationalgeography__lue-671',
'kiwitcms__Kiwi-3729',
'WorksApplications__sudachi.rs-263',
'starsimhub__starsim-626',
'InsightSoftwareConsortium__ITK-4752',
'NeurodataWithoutBorders__nwbinspector-516',
'plone__plone.restapi-1815',
'pytorch__tensordict-1109',
'kokorin__dbt-pumpkin-49',
'servo__servo-34122',
'epignatelli__navix-87',
'StackStorm__st2-6259',
'openwsn-berkeley__lakers-284',
'jdrouet__mrml-477',
'pyccel__pyccel-1808',
'developmentseed__cql2-rs-25',
'sparckles__Robyn-881',
'hand-e-fr__OpenHosta-168',
'DataDog__guarddog-316',
'nasa__fprime-2866',
'delvtech__pypechain-111',
'apytypes__apytypes-542',
'openpathsampling__openpathsampling-1148',
'rapidsai__cudf-16680',
'facelessuser__coloraide-443',
'risingwavelabs__risingwave-19740',
'risingwavelabs__risingwave-19601',
'risingwavelabs__risingwave-19534',
'risingwavelabs__risingwave-19431',
'bab2min__tomotopy-220',
'ionos-cloud__dim-283',
'ipeaGIT__geobr-349',
'pySTEPS__pysteps-356',
'earth-mover__icechunk-465',
'sockheadrps__rpaudio-17',
'orhun__git-cliff-680',
'honeycombio__terraform-provider-honeycombio-496',
'niccokunzmann__python-recurring-ical-events-146',
'zpieslak__mobilus-client-10',
'AbsaOSS__pramen-465',
'eddieantonio__fst-lookup-22',
'NVIDIA__NeMo-Aligner-431',
'felixbur__nkululeko-162',
'alibaba__GraphScope-3667',
'IntelPython__dpnp-1831',
'apache__hudi-rs-52',
'ERGO-Code__HiGHS-1919',
'AnBowell__whittaker-eilers-8',
'dbt-labs__dbt-spark-1042',
'alanjds__drf-nested-routers-339',
'fractal-analytics-platform__fractal-client-717',
'BBVA__mercury-robust-10',
'OpenZeppelin__cairo-contracts-1152',
'Ljzd-PRO__nonebot-plugin-mystool-301',
'feagi__feagi-467',
'apache__iceberg-11467',
'apache__iceberg-10625',
'skalenetwork__IMA-1741',
'skalenetwork__IMA-1734',
'mwouts__itables-303',
'Isotr0py__pillow-jpegxl-plugin-48',
'jorenham__optype-55',
'rmjarvis__Piff-170',
'HDembinski__numba-stats-109',
'ruleminer__InterpreTS-45',
'roskakori__pygount-146',
'single-cell-data__TileDB-SOMA-3319',
'single-cell-data__TileDB-SOMA-3243',
'single-cell-data__TileDB-SOMA-3079',
'drprojects__point_geometric_features-12',
'dice-group__owlapy-65',
'python-trio__flake8-async-292',
'bigmlcom__bigmler-260',
'open-reaction-database__ord-schema-716',
'xgi-org__xgi-574',
'dh-tech__undate-python-88',
'xpodev__seamless-23',
'ploomber__jupysql-plugin-118',
'siapy__siapy-lib-98',
'LedgerHQ__app-ethereum-570',
'nathanramoscfa__pyeconomics-24',
'zooba__pymsbuild-85',
'Mityuha__fresh-bakery-44',
'eoyilmaz__displaycal-py3-374',
'sw360__capycli-89',
'pytorch__TensorRT-3268',
'Deltares__Wflow.jl-498',
'bacalhau-project__bacalhau-4564',
'bacalhau-project__bacalhau-4115',
'bacalhau-project__bacalhau-3628',
'plugwise__python-plugwise-603',
'sparkmicro__Ki-nTree-221',
'supakeen__pinnwand-291',
'alchemistry__alchemlyb-398',
'breez__breez-sdk-greenlight-942',
'aptos-labs__aptos-core-14890',
'jeshraghian__snntorch-305',
'cobbler__cobbler-3770',
'bfGraph__STGraph-142',
'adamchainz__blacken-docs-347',
'desy-ml__cheetah-301',
'google-deepmind__open_spiel-1232',
'Apicurio__apicurio-registry-5350',
'xdslproject__xdsl-3310',
'openlawlibrary__taf-479',
'hhursev__recipe-scrapers-1134',
'kaiachain__kaia-sdk-18',
'KhronosGroup__SPIRV-Tools-5684',
'django-import-export__django-import-export-1979',
'PolicyEngine__policyengine-us-5318',
'vc1492a__PyNomaly-58',
'jubako__arx-95',
'marrink-lab__vermouth-martinize-621',
'tapdata__tapdata-2263',
'siapy__siapy-lib-156',
'SciTools__iris-5740',
'NREL__OpenStudio-5118',
'googleapis__python-spanner-1186',
'NordicHPC__sonar-190',
'deephaven__deephaven-plugins-530',
'Cosmian__kms-306',
'microsoft__regorus-221',
'MachineLearningLifeScience__poli-237',
'WenjieDu__PyPOTS-550',
'WenjieDu__PyPOTS-465',
'tequilahub__tequila-372',
'PlasmaFAIR__fortitude-225',
'awslabs__aws-solutions-constructs-1216',
'kyamagu__skia-python-258',
'computationalgeography__lue-658',
'yasstake__rbot-221',
'braingeneers__braingeneerspy-88',
'dbt-labs__dbt-core-10909',
'WorksApplications__sudachi.rs-245',
'InsightSoftwareConsortium__ITK-5006',
'plone__plone.restapi-1811',
'elastic__elasticsearch-dsl-py-1907',
'ISISComputingGroup__lewis-317',
'LedgerHQ__app-ethereum-696',
'robotpy__mostrobotpy-100',
'StackStorm__st2-6254',
'DGtal-team__DGtal-1726',
'openwisp__openwisp-firmware-upgrader-255',
'cdklabs__cdk-monitoring-constructs-544',
'developmentseed__cql2-rs-37',
'benber86__mamushi-35',
'Cinnamon__kotaemon-144',
'apytypes__apytypes-532',
'rapidsai__cudf-17306',
'risingwavelabs__risingwave-19756',
'risingwavelabs__risingwave-19535',
'bb515__diffusionjax-31',
'theochem__AtomDB-57',
'pittcsc__PittAPI-198',
'teemtee__tmt-2788',
'SciTools__cartopy-2440',
'ludeeus__awesomeversion-334',
'IMMM-SFA__msd_uncertainty_ebook-64',
'GuardKenzie__chafa.py-65',
'AbsaOSS__pramen-449',
'alibaba__GraphScope-4341',
'alibaba__GraphScope-4100',
'Kota-Karthik__twinTrim-73',
'fal-ai__isolate-118',
'briefercloud__briefer-223',
'PECOS-packages__PECOS-64',
'dbt-labs__dbt-spark-1108',
'NVIDIA__NVFlare-2817',
'popsim-consortium__stdpopsim-1570',
'OpenZeppelin__cairo-contracts-1201',
'apache__iceberg-11603',
'apache__iceberg-11495',
'apache__iceberg-10985',
'apache__iceberg-10349',
'my-dev-app__AProxyRelay-77',
'Urban-Analytics-Technology-Platform__poppusher-157',
'DerekStride__tree-sitter-sql-259',
'mwouts__itables-324',
'duckdb__duckdb-14338',
'iree-org__iree-19438',
'jorenham__optype-182',
'moi15moi__FindSystemFontsFilename-16',
'multiversx__mx-sdk-py-cli-423',
'TDAmeritrade__stumpy-986',
'freelawproject__juriscraper-998',
'davidusb-geek__emhass-307',
'google__sedpack-58',
'randyzwitch__streamlit-folium-237',
'coiled__benchmarks-1568',
'nasa-jpl__rosa-20',
'rabbitmq-community__rstream-194',
'elalish__manifold-918',
'GWeindel__hmp-159',
'xgi-org__xgi-600',
'OCA__intrastat-extrastat-276',
'LibreTranslate__LibreTranslate-680',
'kazewong__flowMC-161',
'bigbio__ibaqpy-59',
'openschc__openschc-162',
'MET-OM__metocean-stats-33',
'IN-CORE__pyincore-541',
'MannLabs__alphadia-204',
'HaoboGu__rmk-152',
'kcl-lang__kcl-1816',
'kcl-lang__kcl-1818',
'robustmq__robustmq-859',
'robustmq__robustmq-829',
'starkware-libs__cairo-7045',
'aisk__rust-memcache-141',
'06chaynes__http-cache-87',
'J-F-Liu__lopdf-347',
'unum-cloud__usearch-436',
'GyulyVGC__sniffnet-720',
'biomejs__biome-4578',
'tensorzero__tensorzero-912',
'wasmerio__wasmer-5413',
'wasmerio__wasmer-5079',
'seanmonstar__reqwest-2174',
'huggingface__candle-2714',
'contentauth__c2pa-rs-767',
'trailofbits__cargo-unmaintained-325',
'TraceMachina__nativelink-1420',
'importantimport__hatsu-71',
'RustPython__RustPython-5390',
'apache__opendal-5530',
'alexpasmantier__television-303',
'mitsuhiko__minijinja-554',
'bearcove__loona-218',
'RustCrypto__password-hashes-500',
'ast-grep__ast-grep-1561',
'GuillaumeGomez__sysinfo-1353',
'rustls__rustls-2285',
'GuillaumeGomez__sysinfo-1455',
'zng-ui__zng-517',
'zng-ui__zng-472',
'zng-ui__zng-532',
'zng-ui__zng-177',
'zng-ui__zng-114',
'njord-rs__njord-134',
'dusk-network__rusk-3352',
'dusk-network__rusk-3300',
'esp-rs__espflash-763',
'calyxir__calyx-2399',
'seanmonstar__reqwest-2162',
'mitsuhiko__minijinja-554',
'nervosnetwork__ckb-4486',
'tursodatabase__limbo-937',
'rust-bitcoin__rust-bitcoin-3943',
'njord-rs__njord-176',
'zcash__zcash-6953',
'bilelmoussaoui__oo7-104',
'dprint__dprint-852',
'cryspen__hax-1101',
'sharkdp__bat-3209',
'c410-f3r__wtx-273',
'rust-bitcoin__rust-bitcoin-3954',
'rust-bitcoin__rust-bitcoin-3978',
'slint-ui__slint-7208',
'dathere__qsv-2364',
'IgnisDa__ryot-1223',
'IgnisDa__ryot-1197',
'IgnisDa__ryot-1074',
'IgnisDa__ryot-939',
'bencherdev__bencher-501',
'tursodatabase__limbo-1003',
'apache__datafusion-14902',
'ashvardanian__StringZilla-128',
'ast-grep__ast-grep-1587',
'atomicdata-dev__atomic-server-1031',
'thomas-mauran__chess-tui-107',
'Tencent__tquic-325',
'fujiapple852__trippy-1181',
'Gankra__abi-cafe-54',
'jdrouet__mrml-420',
'kcl-lang__kcl-1828',
'shssoichiro__oxipng-642',
'robustmq__robustmq-594',
'robustmq__robustmq-842',
'modiimedia__arri-80',
'GyulyVGC__sniffnet-659',
'biomejs__biome-4474',
'tensorzero__tensorzero-846',
'wasmerio__wasmer-5194',
'wasmerio__wasmer-5102',
'qarmin__czkawka-1355',
'zng-ui__zng-368',
'seanmonstar__reqwest-2562',
'serenity-rs__serenity-2810',
'serenity-rs__serenity-2882',
'eza-community__eza-1177',
'rune-rs__rune-831',
'TraceMachina__nativelink-1398',
'bearcove__loona-179',
'azalea-rs__azalea-158',
'scs__substrate-api-client-802',
'risingwavelabs__risingwave-20453',
'vectordotdev__vector-22392',
'slint-ui__slint-7292',
'slint-ui__slint-7293',
'mitsuhiko__minijinja-574',
'mitsuhiko__minijinja-432',
'denoland__deno-28189',
'ast-grep__ast-grep-1323',
'rustls__rustls-2278',
'ruffle-rs__ruffle-18622',
'aisk__rust-memcache-145',
'zng-ui__zng-535',
'zng-ui__zng-127',
'zng-ui__zng-136',
'JonahPlusPlus__bevy_atmosphere-79',
'atomicdata-dev__atomic-server-1025',
'dusk-network__rusk-3506',
'dusk-network__rusk-3330',
'aome510__spotify-player-552',
'dusk-network__rusk-3471',
'databendlabs__databend-16963',
'ruffle-rs__ruffle-19349',
'thewh1teagle__rookie-79',
'dalek-cryptography__curve25519-dalek-695',
'tursodatabase__limbo-1034',
'risingwavelabs__risingwave-20642',
'clarkmcc__cel-rust-66',
'vincent-herlemont__native_db-160',
'metalbear-co__mirrord-3000',
'tokio-rs__prost-1037',
'Spotifyd__spotifyd-1284',
'elastio__bon-33',
'BurntSushi__jiff-232',
'dprint__dprint-857',
'cryspen__hax-1293',
'cryspen__hax-1296',
'AFLplusplus__LibAFL-2488',
'wcampbell0x2a__backhand-691',
'GraphiteEditor__Graphite-1986',
'dathere__qsv-2529',
'dathere__qsv-2472',
'dathere__qsv-1975',
'IgnisDa__ryot-1227',
'IgnisDa__ryot-1242',
'IgnisDa__ryot-1149',
'holochain__holochain-4702',
'thomas-mauran__chess-tui-119',
'tauri-apps__tauri-11645',
'tauri-apps__tauri-12323',
'Gankra__abi-cafe-39',
'ashvardanian__StringZilla-130',
'IgnisDa__ryot-1075',
'Rust-SDL2__rust-sdl2-1406',
'BurntSushi__jiff-276']

# cat cpp.jsonl.7.jsonl cpp.jsonl.8.jsonl >> cpp_WENDONG.jsonl
# cat go.jsonl.7.jsonl go.jsonl.8.jsonl >> go_WENDONG.jsonl
# cat python.jsonl.7.jsonl python.jsonl.8.jsonl >> python_WENDONG.jsonl
# cat rust.jsonl.7.jsonl rust.jsonl.8.jsonl >> rust_WENDONG.jsonl
# swing_bench_annotated_jsonl_part_list = [
#     'swing-bench-annotated-jsonl-part/cpp.jsonl.7.jsonl',
#     'swing-bench-annotated-jsonl-part/cpp.jsonl.8.jsonl',
#     'swing-bench-annotated-jsonl-part/go.jsonl.7.jsonl',
#     'swing-bench-annotated-jsonl-part/go.jsonl.8.jsonl',
#     'swing-bench-annotated-jsonl-part/python.jsonl.7.jsonl',
#     'swing-bench-annotated-jsonl-part/python.jsonl.8.jsonl',
#     'swing-bench-annotated-jsonl-part/rust.jsonl.7.jsonl',
#     'swing-bench-annotated-jsonl-part/rust.jsonl.8.jsonl',
# ]


swing_bench_annotated_jsonl_part_list = [
    '/home/mnt/wdxu/dataset/swing-bench-annotated-jsonl/cpp_WENDONG.jsonl',
    '/home/mnt/wdxu/dataset/swing-bench-annotated-jsonl/go_WENDONG.jsonl',
    '/home/mnt/wdxu/dataset/swing-bench-annotated-jsonl/python_WENDONG.jsonl',
    '/home/mnt/wdxu/dataset/swing-bench-annotated-jsonl/rust_WENDONG.jsonl'
]

output_swing_bench_annotated_jsonl_part_list = [
    '/home/mnt/wdxu/dataset/swing-bench-annotated-jsonl/cpp_WENDONG_output.jsonl',
    '/home/mnt/wdxu/dataset/swing-bench-annotated-jsonl/go_WENDONG_output.jsonl',
    '/home/mnt/wdxu/dataset/swing-bench-annotated-jsonl/python_WENDONG_output.jsonl',
    '/home/mnt/wdxu/dataset/swing-bench-annotated-jsonl/rust_WENDONG_output.jsonl'
]






def _get_ci_job_name_id_dict(target_dir, act_list_path):
    def _extract_jobs(filename):
        jobs = {}
        with open(filename, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("Stage"):
                    continue
                columns = re.split(r'\s{2,}', line)
                if len(columns) >= 3:
                    job_id = columns[1]
                    job_name = columns[2]
                    jobs[job_name] = job_id
        return jobs

    script = ["#!/bin/bash"]
    script.extend(["cd " + target_dir])
    script.extend([f"act --list > {act_list_path}"])
    os.system("\n".join(script))
    # only absolute path? 
    act_list_path = os.path.join(target_dir, act_list_path)
    ci_dict = _extract_jobs(os.path.expanduser(act_list_path))
    os.system("rm " + act_list_path)

    return ci_dict

sample_file = """
```json
{
  "reasoning_trace": "The issue arises because the code does not account for the vertical alignment of the text labels and the knobs. The text labels are positioned correctly, but the knobs are not horizontally centered directly beneath the center of their respective labels. This is likely due to the lack of vertical alignment calculations in the code.",
  "code_edits": [
    {
      "file": "libs/sapphire/util/make_sapphire_svg.py",
      "code_to_be_modified": "text += '{:8.3f}'.format(comp.cx)\n            text += ', '\n            text += '{:8.3f}'.format(comp.cy)\n            text += '}},\\n'",
      "code_edited": "text += '{:8.3f}'.format(comp.cx)\n            text += ', '\n            text += '{:8.3f}'.format(comp.cy - label_height / 2)  # Adjust for vertical alignment\n            text += '}},\\n'"
    }
  ]
}
```
"""

if __name__ == "__main__":

    # target_dir = '/mnt/Data/wdxu/github/Swing-Bench/testbed/lightningnetwork__lnd'
    # act_list_path = './act_list.txt'
    # ci_dict = _get_ci_job_name_id_dict(target_dir, act_list_path)
    # print(ci_dict)
    
    # import re
    # pattern = r'```json(.*?)```'
    # match = re.search(pattern, sample_file, re.DOTALL)
    # print(match.group(1).strip())

    # origin_path = "/home/mnt/wdxu/github/SwingBench-data"
    # origin_dataset = load_swingbench_dataset(origin_path, sub_dataset_identifier="python", split=None)
    
    # filtered_path = "/mnt/Data/wdxu/github/filtered_swingbench/filtered_python_instance_list.jsonl"
    # filtered_dataset = load_swingbench_dataset_json(filtered_path)
    
    # print(origin_dataset[0])
    # print('')

    # print(filtered_dataset[0])
    

    # print(origin_dataset[0].ci_name_list, type(origin_dataset[0].ci_name_list))
    # print(filtered_dataset[0].ci_name_list, type(filtered_dataset[0].ci_name_list))


    import json
    for part_file, output_file in zip(swing_bench_annotated_jsonl_part_list, output_swing_bench_annotated_jsonl_part_list):
        new_list = []
        with open(part_file, 'r', encoding='utf-8') as f:
            for line in f:
                data = json.loads(line.strip())
                if data['instance_id'] in ignored_instance_id:
                    continue
                else:
                    new_list.append(data)                    
        with open(output_file, 'w', encoding='utf-8') as f:
            for data in new_list:
                f.write(json.dumps(data) + '\n')
